-- DESABILITANDO O MODE SEGURO
SET SQL_SAFE_UPDATES = 0;

-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DADOS_ESTACIONAMENTO;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DADOS_ESTACIONAMENTO;

-- CONECTANDO AO BANCO DE DADOS
USE DADOS_ESTACIONAMENTO;

-- CRIANDO AS TABELA
CREATE TABLE ENTRADA (
IDENTRADA INT NOT NULL AUTO_INCREMENT PRIMARY KEY
	, NOMECLIENTE VARCHAR(120) NOT NULL
    , PLACA VARCHAR(10) NOT NULL
    , TIPOVEICULO VARCHAR(10) NOT NULL
    , DTENTRADA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- TARIFA
CREATE TABLE TARIFA(
IDTARIFA INT AUTO_INCREMENT PRIMARY KEY
	, DESCRICAO VARCHAR(100)
    , VALORHORA DECIMAL(10,2)
);
INSERT INTO TARIFA (DESCRICAO, VALORHORA) VALUES
('PADRAO', 10.00);

SELECT * FROM ENTRADA;

DESCRIBE ENTRADA;

USE DADOS_ESTACIONAMENTO;

SHOW TABLES;

DESCRIBE ENTRADA;

SELECT DATABASE();
